version: "3.5"
services:
  php:
    container_name: php_test
    build:
      context: .
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - nginx

networks:
  nginx:
    driver: bridge
volumes:
  mysql_data:
